### PR TITLE
Fix Workflow output matching on call aliases Closes #22

### LINKED ISSUE #22: workflow output pattern matching incorrectly matching aliased tasks with common prefixes
From @jsotobroad :

> I had two separate calls defined as
> 
> call MatrixRotation as RotateGVCF
> call MatrixRotation as RotateGVCFIndex
> 
> my output block looks like
> 
> output {
> RotateGVCF.*
> }
> 
> and this will produce the outputs of both of the calls. If I changed the name of RotateGVCFIndex to RotateIndex then only the output of RotateGVCF would be shown as expected.

### PR DESCRIPTION
**Pull request by Horneth**

### CODE REVIEW

File: src/test/scala/wdl4s/WorkflowOutputDeclarationSpec.scala [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+import org.scalatest.{Matchers, FlatSpec}
+
+class WorkflowOutputDeclarationSpec extends FlatSpec with Matchers {
+
+  "WorkflowOutputDeclaration" should "match outputs" in {
+    val declaration = WorkflowOutputDeclaration("wf.mytask", wildcard = true)
+
+    declaration.outputMatchesDeclaration("wf.mytask.a", wildcardsAllowed = true) shouldBe true
+    declaration.outputMatchesDeclaration("wf.mytask.a", wildcardsAllowed = false) shouldBe false
+    declaration.outputMatchesDeclaration("wf.mytaskwithadifferentname.a", wildcardsAllowed = true) shouldBe false
```
Comment (mcovarr) [inline src/test/scala/wdl4s/WorkflowOutputDeclarationSpec.scala]: `wildcardsAllowed=false` test for mytaskwithadifferentname just to be paranoid?  :smile:

**Comment by mcovarr** [comment]
:+1:

**Comment by scottfrazer** [comment]
:+1:
